# Generated by Django 4.2.4 on 2023-08-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('barra', models.FloatField(blank=True, null=True)),
                ('cantidad_inicial', models.FloatField(blank=True, null=True)),
                ('cantidad_min', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caducidad', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
