# Generated by Django 4.2.4 on 2023-10-06 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad_1',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad_2',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad_3',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad_4',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad_5',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_1',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_2',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_3',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_4',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_5',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
